sudo: required
dist: trusty
language: node_js

node_js:
  - "node"

env:
  - CLIENT_DIR=Client SERVER_DIR=Server

addons:
  chrome: stable

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

cache:
  yarn: true

install:
  - cd $TRAVIS_BUILD_DIR/$SERVER_DIR && yarn
  - cd $TRAVIS_BUILD_DIR/$CLIENT_DIR && yarn

script:
  - cd $TRAVIS_BUILD_DIR/$CLIENT_DIR && yarn build --base-href "/test-deployment/"

before_deploy:
  - cd $TRAVIS_BUILD_DIR/$SERVER_DIR

deploy:
  - provider: heroku
    skip-cleanup: true
    api_key:
      secure: $HEROKU_TOKEN
    app: stormy-ridge-32955
    on:
      branch: master
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: ../$CLIENT_DIR/dist
    target-branch: gh-pages
    on:
      branch: master